### ISSUE TITLE
Generated Reader Tests

### ISSUE THREAD

**Issue by robertkossendey** [MrPowers/levi#4]
Are [those folders](https://github.com/MrPowers/levi/tree/main/tests/reader_tests/generated) meant to be part of the repository? 
If not, can we remove them? 
If so, what are they 😅 ?

**Comment by MrPowers** [comment]
@robertkossendey - great question.  Those folders are sample Delta tables actually from the [Delta Acceptance Testing project](https://github.com/delta-incubator/dat/).  We're can use these "standard tables" to write levi tests rather than generating all these reference tables from scratch.  We should probably pick a better table naming convention though!  You should jump into the #dat Slack channel.  I will post a message there now.
